logging:
  level: INFO
  loggers:
    com: DEBUG

server:
  rootPath: /api/*

dateFormat: yyyy-MM-dd'T'HH:mmZ

# DB Configuration
database:
  # The name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # MySQL user details
  user: root
  # Password- no password
  password:
  # the JDBC URL- DB is event_db
  url: jdbc:mysql://localhost:3306/event_db
